language: java
env:
  global:
    # GITHUB_TOKEN
    - secure: "sLQlgb6CU0tHrF4tXwJno/Xqme+mmgu74Qd9H9KuJexfb4OyYw593Q6tn3wMWrImyZlTmcbum1EYIFsgJGhCn8kMuF6PuOywGFPC44LooyBL9Pg4RTYeigQaAEwV4Nfofb7wf7Od09WVbwrb2+e25ya9b7DqtMEVAeFCXqVeGWtudHk+yxyG6N9usA3zvwMGd/Ku3s2WPlviNbGyd0h2aRBuhiAZcgC8OPSgwZNXm2nFgRs/GSxo40LeUSnoO8ilJ4Mp4JbGswXjacj21RGmVCXtwhIOJsy4dk8I0RApv04fCq9/e37K+N0K8Zf4l+n7DyfJzXAT8j/mSzea1RQQlv5lOkj4vBV6q6PBvBgnjrg/1POoP83cPHoJHv/6dbsQJ1GbBDDAbCIuyqXaLDrixvTXJc7x8SPnFUJHXOjzwcsX+oOo7DRqvwS1B4CUYbWnjvxxwHAxbDzW2G3iUKaNdtvBk1Ht/6AFnl2GqSlcEZDfwjIHtOcLNyAhMn2sw9Fjqsn+wXRH0ya9+VlgL+z8VvnJHzhrqUhrn1QJ+1YrpWShsJv61JKoMzQLvgiWoahjcXAnQ0YfAf+SUDlYrGvSgIZdJJfTcHFsdiXyJZuXwmeTNPeOrBS/WNVMJJWwCiYw/Z9KgRZdh8+/EhRSgLBZ0uSfIRbO37uOpdTWHkIFB4w="
before_deploy: "./gradlew shadowJar"
after_deploy: ./after_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: qvr18ooYvp+7hKbhulo9dKeiBrimnhEOFDfdq6TQk3mxul7zrY7Xe8ubPCubYqGbZR7vPIXUoprF+A7CZMizNbqiZGtljqw+svC4OlcPYQF8zKxwqGrQ98xf5bQB5X8lihZ4qVrcZy6XLHVKJXrEnMk61X0iD0RBUfBODG7J9njlRXtaeBcgpoTafd1dzVE5qnSEFLS93QCyg2NvbWTwh0XHhB+wNZN28Ij7E9HJdKm8RxK57wgXpvQ/025U1UseQc8Q77aHYRtgtaR+1YGBUMcqb1AfTZ4cHhAhlrrGErNMRqQFOFHzSsJl3d5JMAJYHAPNlGbeODVbhIGmST3WZHqiBHEJrjB1elbX5MnCpeMg0T7LlhwdiiZvm2m8/8mjxNxxb9RQdWROJtx0XTESTU2lQwsefZ0qoiTpDiuuFzLlNC3C2ri3EBWxFwunVF2VWjw46UYeb9/n6kOAcPZR1Te1YseOWKD6wo8qUhaeq1XvUKs5R8q2LDjmizu58wekFpDdmk3tqFRTUNSW5Ii+BnQXA0PIE42NHRKAlrRZ4nOeDhmPVY0Dkpqim5qhQa8+ijbba+CITUSrNatw7j4ySjdKCTZ49wX4ssrYL3XtXBOgOCL+ArFU5t1im9Yf/HKmCfeVwuaq+IqlzmJitt89ptrRcNDr2Dt5xURaqBQu/5Y=
  file: "./build/libs/stellar-sdk.jar"
  skip_cleanup: true
  on:
    repo: stellar/java-stellar-sdk
    tags: true
